CREATE TABLE Logs (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
log LONGTEXT NOT NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
